name: 🚀 Update StreamedSU Playlist 📺

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour on the hour (UTC)
  workflow_dispatch:       # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Python dependencies & Playwright browsers
        run: |
          python -m pip install --upgrade pip
          pip install playwright urllib3 aiohttp
          playwright install firefox
          playwright install-deps

      - name: 🎯 Run scraping script
        run: python streamsu.py

      - name: 💾 Commit & push if playlist changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add StreamedSU.m3u8
          git diff --cached --quiet && echo "✅ No changes in playlist" || (
            git commit -m "🔁 Update playlist $(date -u)" &&
            git push --force origin main
          )
